# Generated by Django 4.0.4 on 2022-05-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('story', models.TextField(verbose_name='Краткое содержание')),
            ],
            options={
                'verbose_name': 'Сказка',
                'verbose_name_plural': 'Сказки',
            },
        ),
    ]
