# Generated by Django 4.0.4 on 2022-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='category',
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.TextField(verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='story',
            name='classif',
            field=models.TextField(verbose_name='Категория'),
        ),
    ]
