# Generated by Django 4.0.4 on 2022-05-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_story_category_alter_story_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.CharField(max_length=150, verbose_name='Автор'),
        ),
    ]
