# Generated by Django 4.0.4 on 2022-12-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_resume_alter_story_managers_alter_story_classif'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('tagId', models.AutoField(db_column='tagId', primary_key=True, serialize=False)),
                ('tagName', models.TextField(db_column='tagName', unique=True)),
            ],
            options={
                'db_table': 'texts_tags',
                'managed': True,
            }
        )
    ]
