# Generated by Django 4.0.4 on 2023-01-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('tagName', models.TextField(db_column='tagName', unique=True)),
                ('tagId', models.AutoField(db_column='tagId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'texts_tags',
                'managed': True,
            },
        ),
    ]
